### ISSUE TITLE
get_vpn_config_details fails on wget

### ISSUE THREAD

**Issue by WeirdCarrotMonster** [ProtonVPN/protonvpn-cli#102]
On one of my systems (Archlinux, wget 1.19.4), function `get_vpn_config_details` fails, because calling `wget` with `-O /dev/stdout` gives no output. Calling it with `-O -` works as expected.

While using /dev/stdout should actually work, `man wget` suggests using `-`:

> If - is used as file, documents will be printed to standard output, disabling link conversion.

On a side note: why not use `curl` instead of `wget`? AFAIK `curl` is included in most base linux systems, while `wget` needs to be installed separately.

**Comment by mazen160** [comment]
Hi @WeirdCarrotMonster 

This is a weird issue for sure. I haven't seen this reproducing before.

1) `/dev/stdout` should work on all cases. I don't know why it's not working on this case. I added `/dev/stdout` instead of `-` so that lightweight forks of wget should work too when `-` is not implemented. Just as an extra case.

2) `wget` is used instead of `curl` as `wget` is more pre-installed on distros than `curl`.
The offchances that you find `wget` not installed on a system is quite low. Do you have any distros that don't have `wget` pre-installed?

I like `curl`, in fact I find it much easier for anything. I just chosen `wget` to the factor of having it more pre-installed than `curl`.


Would you mind executing the following on your system and let us know the results?

```bash

$ wget --header 'x-pm-appversion: Other' \
                         --header 'x-pm-apiversion: 3' \
                         --header 'Accept: application/vnd.protonmail.v1+json' \
                         --timeout 20 --tries 1 -q -O /dev/stdout "https://api.protonmail.ch/vpn/logicals" 


$ echo $?
```

**Comment by mazen160** [comment]
Hi @WeirdCarrotMonster 

Just letting you know that the change is now live.

Thanks,
Mazin
