### ISSUE TITLE
Keeping track/checking public keys(w/ configurations)

### ISSUE THREAD

**Issue by o-jasper** [ProtonVPN/protonvpn-cli#111]
Was wondering how it got the public key, so it `wget`s this url:

    https://api.protonmail.ch/vpn/config?Platform=$(detect_platform_type)&LogicalID=$config_id&Protocol=$selected_protocol"

My old straight-openvpn setup was just the configuration file, with public key in it. This downloads it each time. Maybe it should print/log when it changes so it is a bit more clear what is happening. I guess, though, a double MITM, both the VPN and https://api.protonmail.ch is relatively unlikely.

Another idea is to sign the configurations with GPG and have the application verify it. Or use `https://raw.githubusercontent.com` to put up checksums.

**Comment by mazen160** [comment]
Hi @o-jasper 

The current thread model works on having wget verifying the certificate that validates the transaction. If the system is compromised, then an attacker can does that; but since the system is already compromised, there is nothing much we can do to help.

a MITM will fail because of HTTPS transactions is declared explicitly and checking with enabled.

More checking will not allow a lot much benifit from security perspective.

**Comment by mazen160** [comment]
Hi @o-jasper 

Let's move the conversation to the PR. 

Once the PR is revised, it will be pushed on the next update.

Thanks,
Mazin

PR: https://github.com/ProtonVPN/protonvpn-cli/pull/113
