### ISSUE TITLE
Killswitch not working

### ISSUE THREAD

**Issue by rishispeets** [ProtonVPN/protonvpn-cli#139]
Hey guys,

I have an issue with the killswitch.

**EXPECTED BEHAVIOR**
Disconnecting the VPN connection with `sudo pvpn -d` should disable my internet connection while I have the killswitch turned on.

**ACTUAL BEHAVIOR** 
VPN gets turned off, and my internet connection resumes without it. 

**STEPS UNDERTAKEN TO FIX** 
- I tried uninstalling and reinstalling the script, making sure I answered `yes` for the killswitch feature.
- Private Internet Access was also installed before, with their killswitch enabled. I uninstalled it before reinstalling the protonvpn-cli.

**VERSIONS**
Ubuntu v18.04
protonvpn-cli v1.1.1

**Comment by xilopaint** [comment]
Killswitch is currently disabled due to some bugs. See ffbe6606d3d78de3e110d90d03878be2b16c7863.

**Comment by mazen160** [comment]
Hi @rishispeets 

The killswitch by default is disabled and returns to normal when you connect via `pvpn -d`. 

The killswitch mission is to protect against leakage when openvpn process is killed unexpectedly or anything in this page. When you disconnect from pvpn, it returns everything back to normal.

As @xilopaint said, it's currently disabled due to bugs. It will be re-activated with fix to everything soon.


Best regards,
Mazin
