### ISSUE TITLE
Should we really be mixing python and bash code?

### ISSUE THREAD

**Issue by arderyp** [ProtonVPN/protonvpn-cli#33]
This "issue" is really just cosmetic, and maybe no one else cares, but I feel like mixing python code in with bash code is kind of janky.  It also causes the GitHub project stats to be misleading: 100% shell, and yet we have a python dependency.  None of any of this is truly important to the functioning of the utility, but does anyone else think it might be more clear to move this python code into separate `.py` files?  Or maybe eliminate bash altogether and make this a 100% python script?

**Comment by xilopaint** [comment]
> This "issue" is really just cosmetic

When you suggest a full rewriting it's not cosmetic at all. 😄

**Comment by arderyp** [comment]
Sorry, I just meant cosmetic in that it doesn't make the utility run any differently, add any new functionality, or improve efficiency.  I certainly don't want to ask anyone to rewrite it, as what we have now is already good and clean code that does what we want.  I just instinctively thought, "what's this python code doing in a bash script" when I first encountered it, and figured it might be worth discussing.  But yeah, maintainers, feel free to ignore/close this if its a stupid discussion.

**Comment by Rafficer** [comment]
I think it's the best way because, as you said, python comes pre-installed. Moving it to different files (one bash, few python) is also not the best for usability. Right now you only need to download one file.

**Comment by mazen160** [comment]
@Rafficer 
Yup exactly :)

**Comment by arderyp** [comment]
great, you've convinced me, thanks!

**Comment by mazen160** [comment]
@arderyp 
Awesome!! :)

**Comment by o-jasper** [comment]
Python is not exactly lightweight though. It is literally 100 times the size of lua(jit).. Which seems excessive to be honest. I mean, despite 100MB not being that much nowadays, being able to keep low is a sign of being in control to me..

Nevertheless, it is handy, i think lighter versions exist... So if someone really wants to, maybe (s)he can figure out a way to run it on it one one of them.

I also wonder if alternatively, you could ditch the shell instead of python. `import subprocess` can do things.. But that might be me.

**Comment by mazen160** [comment]
@o-jasper 
But the other part is
1) we need something to be installed in almost all platforms
2) We need to have it to be extensible.

+ there is no much heavy weight computing is done. Only simple deserializing and checking 1k< records. It shouldn't be a problem in our case.
