### ISSUE TITLE
Add -status command

### ISSUE THREAD

**Issue by cantab412** [ProtonVPN/protonvpn-cli#46]
Hi -

It would be great if there was a way to check the VPN status from the command line.

```
$ sudo ./proton-vpn -status
Status: Connected
Location: server-country
IP: ip-address
Protocol: protocol
```
This would allow for scripting status updates (i.e. with Übersicht) or other programmatic functions.

**Comment by mazen160** [comment]
@cantab412 
I added it to road-map. It will be implemented soon.

Thanks,
Mazin

**Comment by mazen160** [comment]
Hi @cantab412 

I implemented a prototype for the `--status` command.

commit: https://github.com/ProtonVPN/protonvpn-cli/commit/d746b905c0cd15ee8b8a44216ec09eb9f20e7e47

It should cover everything but the "Country" and "VPN server tier".  I will be implementing it tomorrow.


Best,
Mazin

**Comment by mazen160** [comment]
I mistakenly clicked "close".

**Comment by mazen160** [comment]
Hi again!

I have taken some time to finish it, now it looks much nicer:)

```bash
$ bash  protonvpn-cli.sh -status
[OpenVPN Status]: Running
[ProtonVPN Status]: Running
[Internet Status]: Online
[Public IP Address]: 1.2.3.4
[ProtonVPN] [Server Name]: CA#5
[ProtonVPN] [OpenVPN Protocol]: UDP
[ProtonVPN] [Exit Country]: CA
[ProtonVPN] [Tier]: 1
[ProtonVPN] [Server Features]: None
[ProtonVPN] [Server Load]: 8
```

**Comment by mazen160** [comment]
If anyone have a cooler design, please let me know :)

**Comment by cantab412** [comment]
Nice!  Thanks @mazen160 

Is there any way that ```--status``` can run as a user instead of needing root?  I have a bash script that runs under Übersicht that shows my VPN status on the desktop.

**Comment by Rafficer** [comment]
f64d50970cb1f9041b391f760fbed9205f5fd3b1 was the additional commit, just to note :)

@cantab412 That doesn't really work as the `--status` command needs to access `~/.protonvpn-cli` which is only accessible by root for security (it contains your OpenVPN username/password)

The output without root would be this:

```
[OpenVPN Status]: Running
[ProtonVPN Status]: Not Running
[Internet Status]: Online
[Public IP Address]: 89.39.107.191
```

instead of this:

```
[OpenVPN Status]: Running
[ProtonVPN Status]: Running
[Internet Status]: Online
[Public IP Address]: 89.39.107.191
[ProtonVPN] [Server Name]: NL-FREE#1
[ProtonVPN] [OpenVPN Protocol]: UDP
[ProtonVPN] [Exit Country]: NL
[ProtonVPN] [Tier]: 0
[ProtonVPN] [Server Features]: None
[ProtonVPN] [Server Load]: 81
```

(Same session)

To make it run for you, you could exclude the password verification for sudo for the `protonvpn-cli --status` and `pvpn --status` commands. This should help you with that:

https://askubuntu.com/questions/159007/how-do-i-run-specific-sudo-commands-without-a-password

And then you can just use sudo in the script.

Use at your own risk, though :)

**Comment by mazen160** [comment]
@cantab412 
I have thought about this, and also tried it. It would be preferred to follow what @Rafficer shared. I would have done the same too :)

**Comment by mazen160** [comment]
I believe then the issue can be closed as done :)
