### ISSUE TITLE
function init_cli()

### ISSUE THREAD

**Issue by ohdearaugustin** [ProtonVPN/protonvpn-cli#52]
According to the script the config files shoud be stored under the home dir of the user, but the ower is still root. Is it on purpose?

`chown "$USER:$(id -gn $USER)" "$(get_home)/.protonvpn-cli/protonvpn_openvpn_credentials"`

GNU bash, version 4.4.19(1)-release (x86_64-unknown-linux-gnu)

I call the script in the zsh shell with `sudo ./protonvpn-cli.sh -init`.
zsh 5.4.2 (x86_64-unknown-linux-gnu)

OS: Linux HOSTNAME 4.14.29-1-MANJARO #1 SMP PREEMPT Wed Mar 21 16:48:46 UTC 2018 x86_64 GNU/Linux

**Comment by xilopaint** [comment]
Maybe it's the case to change the path, but not the ownership.

**Comment by Rafficer** [comment]
I would say yes. Reasoning for user home would be that multiple users on the same machine can have different credentials stored. **Maybe** kind of an edge-case but anyway. And root is owner for security reasons, because the credentials have to be stored in plaintext in order for openvpn to work.

And the program has to be run as root anyway.

**Comment by ohdearaugustin** [comment]
@Rafficer thank you for the details.

**Comment by mazen160** [comment]
Yes, as @Rafficer explained.
