### ISSUE TITLE
Security of the protonvpn-cli profile folder

### ISSUE THREAD

**Issue by webmaniak** [ProtonVPN/protonvpn-cli#57]
Hello!

While investigating a bit on the source code, I noticed the tool currently stores its data on a `~/.protonvpn-cli/` folder, which is alright. However credentials are stored in plain text. How is ProtonVPN positioned about that? I mean, is it foreseen at some point to have at least the password encrypted or are the credentials considered as "reasonably safe to store in plain text"?

Thanks in advance for your answer.

P.S: please note I'm not blaming anybody, I'm just asking out of curiosity because I noticed that fact. :)

**Comment by mazen160** [comment]
Hi all,

we had a long discussion internally regarding this part. The problem is I didn't find a way to implement credentials encryption in a secure way, and without breaking UX.

The solution is to rely on Linux/Unix provided security. protonvpn-credentials are only accessible by root. 

`openvpn` requires users to have credentials written on a disk, or entering it every-time (which is inconvenient).

protonvpn-cli model on securing credentials is: even if your machine is compromised on user-level, your credentials should be safe, and your openvpn credentials is as safe as the root's account.


Also, `protonvpn-cli` asks for openvpn credentials, not the Proton ID credentials, which decreases the value of the credentials, as openvpn credentials can also be used in ProtonVPN, and is not associate with any ProtonLabs service.

We have on roadmap to add a feature to optionally encrypt the openvpn credentials, but I can't confirm when it will be implemented.

**Comment by webmaniak** [comment]
Hi!

Thanks for your two valuable answers to that question. As far as I am concerned, the choice made about credentials is reasonably secure since:

- the profile folder is indeed accessible only by root (if it gets accessed, you have other more critical issues to address)
- only the OpenVPN credentials are at risk, not your overall ProtonVPN / ProtonMail account (which is great!)

Then I agree we close this topic for now as it has been discussed and I can see it has been *thought about*, which is as pleasant as reassuring.

**Comment by mazen160** [comment]
Great @webmaniak !

and as always, if you have any thoughts, feel free to let us know, and we will make sure to add/change/improve the project :)

Thanks,
Mazin
